// src/PipePair.tsx
import type { MainThread } from '@lynx-js/types';
import type { MainThreadRef } from '@lynx-js/react';

import pipeGreen from '../assets/sprites/pipe-green.png';

interface PipePairProps {
  pipeRef: MainThreadRef<MainThread.Element>;
  topRef: MainThreadRef<MainThread.Element>;
  botRef: MainThreadRef<MainThread.Element>;
  gapRef: MainThreadRef<MainThread.Element>;
}

export function PipePair({ pipeRef, topRef, botRef, gapRef }: PipePairProps) {
  return (
    <view
      className="pipe-pair"
      main-thread:ref={pipeRef}
      style={{ left: '9999px' }}
    >
      <view className="pipe-top" main-thread:ref={topRef}>
        <image src={pipeGreen} className="pipe-top-img" />
      </view>
      <view className="pipe-bottom" main-thread:ref={botRef}>
        <image src={pipeGreen} className="pipe-bottom-img" />
      </view>
      <view className="pipe-gap-zone" main-thread:ref={gapRef} style={{ display: 'none' }} />
    </view>
  );
}

// src/PipePair.vue
<script setup lang="ts">
import type { MTRef } from './types.js'

import pipeGreen from '../assets/sprites/pipe-green.png'

defineProps<{
  pipeRef: MTRef
  topRef: MTRef
  botRef: MTRef
  gapRef: MTRef
}>()
</script>

<template>
  <view class="pipe-pair" :main-thread-ref="pipeRef" :style="{ left: '9999px' }">
    <view class="pipe-top" :main-thread-ref="topRef">
      <image :src="pipeGreen" class="pipe-top-img" />
    </view>
    <view class="pipe-bottom" :main-thread-ref="botRef">
      <image :src="pipeGreen" class="pipe-bottom-img" />
    </view>
    <view class="pipe-gap-zone" :main-thread-ref="gapRef" :style="{ display: 'none' }" />
  </view>
</template>
